[package]
name = "kanata-lsp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kanata-lsp"
path = "src/main.rs"

[dependencies]
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
kanata-parser = "0.1103"
serde_json = "1.0"
